-- Run this in Supabase:
-- Dashboard > SQL Editor > New query > Paste > Run

create table if not exists public.rsvps (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  full_name text not null,
  whatsapp text not null unique,
  email text not null unique,
  attendance text not null check (attendance in ('attending', 'not_attending')),
  guest_count integer not null default 1 check (guest_count between 0 and 10),
  message text,
  table_number text,
  invitation_sent boolean not null default false,
  table_number_sent boolean not null default false
);

-- Turn on Row Level Security
alter table public.rsvps enable row level security;

-- Allow wedding guests to submit an RSVP from the public website.
-- They cannot read, update, or delete the RSVP list.
drop policy if exists "Public can submit RSVP" on public.rsvps;

create policy "Public can submit RSVP"
on public.rsvps
for insert
to anon
with check (
  char_length(full_name) between 2 and 120
  and char_length(whatsapp) between 9 and 20
  and char_length(email) between 5 and 200
  and attendance in ('attending', 'not_attending')
  and guest_count between 0 and 10
);

-- Only signed-in Supabase users can view and manage guest records.
drop policy if exists "Authenticated users can view RSVPs" on public.rsvps;
create policy "Authenticated users can view RSVPs"
on public.rsvps
for select
to authenticated
using (true);

drop policy if exists "Authenticated users can update RSVPs" on public.rsvps;
create policy "Authenticated users can update RSVPs"
on public.rsvps
for update
to authenticated
using (true)
with check (true);

-- Helpful indexes
create index if not exists rsvps_attendance_idx on public.rsvps(attendance);
create index if not exists rsvps_table_number_idx on public.rsvps(table_number);
